<?php
/**
 * CloudRole
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CloudRole model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class CloudRole 
{
        /**
     * @var int|null
     * @SerializedName("cloud")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $cloud = null;

    /**
     * Role of the user in the cloud
     *
     * @var int|null
     * @SerializedName("role")
     * @Assert\Choice({ 100, 50 })
     * @Assert\Type("int")
     * @Type("int")
     * @Assert\GreaterThanOrEqual(-32768)
     * @Assert\LessThanOrEqual(32767)
     */
    protected ?int $role = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->cloud = $data['cloud'] ?? null;
        $this->role = $data['role'] ?? null;
    }

    /**
     * Gets cloud.
     *
     * @return int|null
     */
    public function getCloud(): ?int
    {
        return $this->cloud;
    }

    /**
     * Sets cloud.
     *
     * @param int|null $cloud
     *
     * @return $this
     */
    public function setCloud(?int $cloud): self
    {
        $this->cloud = $cloud;

        return $this;
    }

    /**
     * Gets role.
     *
     * @return int|null
     */
    public function getRole(): ?int
    {
        return $this->role;
    }

    /**
     * Sets role.
     *
     * @param int|null $role  Role of the user in the cloud
     *
     * @return $this
     */
    public function setRole(?int $role = null): self
    {
        $this->role = $role;

        return $this;
    }
}


