<?php
/**
 * Cloud
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Cloud model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class Cloud 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $id = null;

    /**
     * Name of the cloud
     *
     * @var string|null
     * @SerializedName("name")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 256
     * )
     */
    protected ?string $name = null;

    /**
     * @var array|null
     * @SerializedName("features")
     * @Assert\NotNull()
     * @Assert\Valid()
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\Feature")
     * })
     * @Type("array<OpenAPI\Server\Model\Feature>")
     */
    protected ?array $features = null;

    /**
     * @var array|null
     * @SerializedName("marketplace_apps")
     * @Assert\NotNull()
     * @Assert\Valid()
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\MarketplaceApp")
     * })
     * @Type("array<OpenAPI\Server\Model\MarketplaceApp>")
     */
    protected ?array $marketplaceApps = null;

    /**
     * @var 
     * @SerializedName("organization")
     * @Assert\NotNull()
     * @Assert\Valid()
     * @Assert\Type("Organization")
     * @Type("Organization")
     */
    protected  $organization = null;

    /**
     * @var 
     * @SerializedName("creator")
     * @Assert\NotNull()
     * @Assert\Valid()
     * @Assert\Type("User")
     * @Type("User")
     */
    protected  $creator = null;

    /**
     * @var string|null
     * @SerializedName("creator_app")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $creatorApp = null;

    /**
     * @var bool|null
     * @SerializedName("is_default")
     * @Assert\NotNull()
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected ?bool $isDefault = null;

    /**
     * Creation date
     *
     * @var \DateTime|null
     * @SerializedName("created_at")
     * @Assert\NotNull()
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected ?\DateTime $createdAt = null;

    /**
     * @var string|null
     * @SerializedName("image")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $image = null;

    /**
     * Date of the last update
     *
     * @var \DateTime|null
     * @SerializedName("updated_at")
     * @Assert\NotNull()
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected ?\DateTime $updatedAt = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = $data['id'] ?? null;
        $this->name = $data['name'] ?? null;
        $this->features = $data['features'] ?? null;
        $this->marketplaceApps = $data['marketplaceApps'] ?? null;
        $this->organization = $data['organization'] ?? null;
        $this->creator = $data['creator'] ?? null;
        $this->creatorApp = $data['creatorApp'] ?? null;
        $this->isDefault = $data['isDefault'] ?? null;
        $this->createdAt = $data['createdAt'] ?? null;
        $this->image = $data['image'] ?? null;
        $this->updatedAt = $data['updatedAt'] ?? null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id
     *
     * @return $this
     */
    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name  Name of the cloud
     *
     * @return $this
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets features.
     *
     * @return array|null
     */
    public function getFeatures(): ?array
    {
        return $this->features;
    }

    /**
     * Sets features.
     *
     * @param array|null $features
     *
     * @return $this
     */
    public function setFeatures(?array $features): self
    {
        $this->features = $features;

        return $this;
    }

    /**
     * Gets marketplaceApps.
     *
     * @return array|null
     */
    public function getMarketplaceApps(): ?array
    {
        return $this->marketplaceApps;
    }

    /**
     * Sets marketplaceApps.
     *
     * @param array|null $marketplaceApps
     *
     * @return $this
     */
    public function setMarketplaceApps(?array $marketplaceApps): self
    {
        $this->marketplaceApps = $marketplaceApps;

        return $this;
    }

    /**
     * Gets organization.
     *
     * @return 
     */
    public function getOrganization(): 
    {
        return $this->organization;
    }

    /**
     * Sets organization.
     *
     * @param  $organization
     *
     * @return $this
     */
    public function setOrganization( $organization): self
    {
        $this->organization = $organization;

        return $this;
    }

    /**
     * Gets creator.
     *
     * @return 
     */
    public function getCreator(): 
    {
        return $this->creator;
    }

    /**
     * Sets creator.
     *
     * @param  $creator
     *
     * @return $this
     */
    public function setCreator( $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    /**
     * Gets creatorApp.
     *
     * @return string|null
     */
    public function getCreatorApp(): ?string
    {
        return $this->creatorApp;
    }

    /**
     * Sets creatorApp.
     *
     * @param string|null $creatorApp
     *
     * @return $this
     */
    public function setCreatorApp(?string $creatorApp): self
    {
        $this->creatorApp = $creatorApp;

        return $this;
    }

    /**
     * Gets isDefault.
     *
     * @return bool|null
     */
    public function isIsDefault(): ?bool
    {
        return $this->isDefault;
    }

    /**
     * Sets isDefault.
     *
     * @param bool|null $isDefault
     *
     * @return $this
     */
    public function setIsDefault(?bool $isDefault): self
    {
        $this->isDefault = $isDefault;

        return $this;
    }

    /**
     * Gets createdAt.
     *
     * @return \DateTime|null
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets createdAt.
     *
     * @param \DateTime|null $createdAt  Creation date
     *
     * @return $this
     */
    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Gets image.
     *
     * @return string|null
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * Sets image.
     *
     * @param string|null $image
     *
     * @return $this
     */
    public function setImage(?string $image = null): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Gets updatedAt.
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets updatedAt.
     *
     * @param \DateTime|null $updatedAt  Date of the last update
     *
     * @return $this
     */
    public function setUpdatedAt(?\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}


