<?php
/**
 * Component
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Component model.
 *
 * Adds nested create feature
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class Component 
{
        /**
     * @var string|null
     * @SerializedName("ifc_guid")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 255
     * )
     */
    protected ?string $ifcGuid = null;

    /**
     * @var string|null
     * @SerializedName("originating_system")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 255
     * )
     */
    protected ?string $originatingSystem = null;

    /**
     * @var string|null
     * @SerializedName("authoring_tool_id")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 255
     * )
     */
    protected ?string $authoringToolId = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->ifcGuid = $data['ifcGuid'] ?? null;
        $this->originatingSystem = $data['originatingSystem'] ?? null;
        $this->authoringToolId = $data['authoringToolId'] ?? null;
    }

    /**
     * Gets ifcGuid.
     *
     * @return string|null
     */
    public function getIfcGuid(): ?string
    {
        return $this->ifcGuid;
    }

    /**
     * Sets ifcGuid.
     *
     * @param string|null $ifcGuid
     *
     * @return $this
     */
    public function setIfcGuid(?string $ifcGuid = null): self
    {
        $this->ifcGuid = $ifcGuid;

        return $this;
    }

    /**
     * Gets originatingSystem.
     *
     * @return string|null
     */
    public function getOriginatingSystem(): ?string
    {
        return $this->originatingSystem;
    }

    /**
     * Sets originatingSystem.
     *
     * @param string|null $originatingSystem
     *
     * @return $this
     */
    public function setOriginatingSystem(?string $originatingSystem = null): self
    {
        $this->originatingSystem = $originatingSystem;

        return $this;
    }

    /**
     * Gets authoringToolId.
     *
     * @return string|null
     */
    public function getAuthoringToolId(): ?string
    {
        return $this->authoringToolId;
    }

    /**
     * Sets authoringToolId.
     *
     * @param string|null $authoringToolId
     *
     * @return $this
     */
    public function setAuthoringToolId(?string $authoringToolId = null): self
    {
        $this->authoringToolId = $authoringToolId;

        return $this;
    }
}


