<?php
/**
 * MarketplaceAppImageRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the MarketplaceAppImageRequest model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class MarketplaceAppImageRequest 
{
        /**
     * @var UploadedFile|null
     * @SerializedName("image")
     * @Assert\NotNull()
     * @Assert\Type("UploadedFile")
     * @Type("UploadedFile")
     */
    protected ?UploadedFile $image = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->image = $data['image'] ?? null;
    }

    /**
     * Gets image.
     *
     * @return UploadedFile|null
     */
    public function getImage(): ?UploadedFile
    {
        return $this->image;
    }

    /**
     * Sets image.
     *
     * @param UploadedFile|null $image
     *
     * @return $this
     */
    public function setImage(?UploadedFile $image): self
    {
        $this->image = $image;

        return $this;
    }
}


