<?php
/**
 * MaterialListComponent
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the MaterialListComponent model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class MaterialListComponent 
{
        /**
     * @var Material|null
     * @SerializedName("material")
     * @Assert\Type("OpenAPI\Server\Model\Material")
     * @Type("OpenAPI\Server\Model\Material")
     */
    protected ?Material $material = null;

    /**
     * @var MaterialOption|null
     * @SerializedName("option")
     * @Assert\NotNull()
     * @Assert\Valid()
     * @Assert\Type("OpenAPI\Server\Model\MaterialOption")
     * @Type("OpenAPI\Server\Model\MaterialOption")
     */
    protected ?MaterialOption $option = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->material = $data['material'] ?? null;
        $this->option = $data['option'] ?? null;
    }

    /**
     * Gets material.
     *
     * @return Material|null
     */
    public function getMaterial(): ?Material
    {
        return $this->material;
    }

    /**
     * Sets material.
     *
     * @param Material|null $material
     *
     * @return $this
     */
    public function setMaterial(?Material $material = null): self
    {
        $this->material = $material;

        return $this;
    }

    /**
     * Gets option.
     *
     * @return MaterialOption|null
     */
    public function getOption(): ?MaterialOption
    {
        return $this->option;
    }

    /**
     * Sets option.
     *
     * @param MaterialOption|null $option
     *
     * @return $this
     */
    public function setOption(?MaterialOption $option): self
    {
        $this->option = $option;

        return $this;
    }
}


