<?php
/**
 * ModelFiles
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ModelFiles model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class ModelFiles 
{
        /**
     * @var string|null
     * @SerializedName("structure_file")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $structureFile = null;

    /**
     * @var string|null
     * @SerializedName("systems_file")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $systemsFile = null;

    /**
     * @var string|null
     * @SerializedName("map_file")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $mapFile = null;

    /**
     * @var string|null
     * @SerializedName("gltf_file")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $gltfFile = null;

    /**
     * @var string|null
     * @SerializedName("gltf_with_openings_file")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $gltfWithOpeningsFile = null;

    /**
     * @var string|null
     * @SerializedName("bvh_tree_file")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $bvhTreeFile = null;

    /**
     * @var string|null
     * @SerializedName("preview_file")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $previewFile = null;

    /**
     * @var string|null
     * @SerializedName("xkt_file")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $xktFile = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->structureFile = $data['structureFile'] ?? null;
        $this->systemsFile = $data['systemsFile'] ?? null;
        $this->mapFile = $data['mapFile'] ?? null;
        $this->gltfFile = $data['gltfFile'] ?? null;
        $this->gltfWithOpeningsFile = $data['gltfWithOpeningsFile'] ?? null;
        $this->bvhTreeFile = $data['bvhTreeFile'] ?? null;
        $this->previewFile = $data['previewFile'] ?? null;
        $this->xktFile = $data['xktFile'] ?? null;
    }

    /**
     * Gets structureFile.
     *
     * @return string|null
     */
    public function getStructureFile(): ?string
    {
        return $this->structureFile;
    }

    /**
     * Sets structureFile.
     *
     * @param string|null $structureFile
     *
     * @return $this
     */
    public function setStructureFile(?string $structureFile = null): self
    {
        $this->structureFile = $structureFile;

        return $this;
    }

    /**
     * Gets systemsFile.
     *
     * @return string|null
     */
    public function getSystemsFile(): ?string
    {
        return $this->systemsFile;
    }

    /**
     * Sets systemsFile.
     *
     * @param string|null $systemsFile
     *
     * @return $this
     */
    public function setSystemsFile(?string $systemsFile = null): self
    {
        $this->systemsFile = $systemsFile;

        return $this;
    }

    /**
     * Gets mapFile.
     *
     * @return string|null
     */
    public function getMapFile(): ?string
    {
        return $this->mapFile;
    }

    /**
     * Sets mapFile.
     *
     * @param string|null $mapFile
     *
     * @return $this
     */
    public function setMapFile(?string $mapFile = null): self
    {
        $this->mapFile = $mapFile;

        return $this;
    }

    /**
     * Gets gltfFile.
     *
     * @return string|null
     */
    public function getGltfFile(): ?string
    {
        return $this->gltfFile;
    }

    /**
     * Sets gltfFile.
     *
     * @param string|null $gltfFile
     *
     * @return $this
     */
    public function setGltfFile(?string $gltfFile = null): self
    {
        $this->gltfFile = $gltfFile;

        return $this;
    }

    /**
     * Gets gltfWithOpeningsFile.
     *
     * @return string|null
     */
    public function getGltfWithOpeningsFile(): ?string
    {
        return $this->gltfWithOpeningsFile;
    }

    /**
     * Sets gltfWithOpeningsFile.
     *
     * @param string|null $gltfWithOpeningsFile
     *
     * @return $this
     */
    public function setGltfWithOpeningsFile(?string $gltfWithOpeningsFile = null): self
    {
        $this->gltfWithOpeningsFile = $gltfWithOpeningsFile;

        return $this;
    }

    /**
     * Gets bvhTreeFile.
     *
     * @return string|null
     */
    public function getBvhTreeFile(): ?string
    {
        return $this->bvhTreeFile;
    }

    /**
     * Sets bvhTreeFile.
     *
     * @param string|null $bvhTreeFile
     *
     * @return $this
     */
    public function setBvhTreeFile(?string $bvhTreeFile = null): self
    {
        $this->bvhTreeFile = $bvhTreeFile;

        return $this;
    }

    /**
     * Gets previewFile.
     *
     * @return string|null
     */
    public function getPreviewFile(): ?string
    {
        return $this->previewFile;
    }

    /**
     * Sets previewFile.
     *
     * @param string|null $previewFile
     *
     * @return $this
     */
    public function setPreviewFile(?string $previewFile = null): self
    {
        $this->previewFile = $previewFile;

        return $this;
    }

    /**
     * Gets xktFile.
     *
     * @return string|null
     */
    public function getXktFile(): ?string
    {
        return $this->xktFile;
    }

    /**
     * Sets xktFile.
     *
     * @param string|null $xktFile
     *
     * @return $this
     */
    public function setXktFile(?string $xktFile = null): self
    {
        $this->xktFile = $xktFile;

        return $this;
    }
}


