<?php
/**
 * PatchedVisaRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the PatchedVisaRequest model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class PatchedVisaRequest 
{
        /**
     * This is the userproject_id. This field is only used if the call is made from an App
     *
     * @var int|null
     * @SerializedName("creator_id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $creatorId = null;

    /**
     * Description of the visa
     *
     * @var string|null
     * @SerializedName("description")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $description = null;

    /**
     * @var \DateTime|null
     * @SerializedName("deadline")
     * @Assert\Date()
     * @Type("DateTime<'Y-m-d'>")
     */
    protected ?\DateTime $deadline = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->creatorId = $data['creatorId'] ?? null;
        $this->description = $data['description'] ?? null;
        $this->deadline = $data['deadline'] ?? null;
    }

    /**
     * Gets creatorId.
     *
     * @return int|null
     */
    public function getCreatorId(): ?int
    {
        return $this->creatorId;
    }

    /**
     * Sets creatorId.
     *
     * @param int|null $creatorId  This is the userproject_id. This field is only used if the call is made from an App
     *
     * @return $this
     */
    public function setCreatorId(?int $creatorId = null): self
    {
        $this->creatorId = $creatorId;

        return $this;
    }

    /**
     * Gets description.
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets description.
     *
     * @param string|null $description  Description of the visa
     *
     * @return $this
     */
    public function setDescription(?string $description = null): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Gets deadline.
     *
     * @return \DateTime|null
     */
    public function getDeadline(): ?\DateTime
    {
        return $this->deadline;
    }

    /**
     * Sets deadline.
     *
     * @param \DateTime|null $deadline
     *
     * @return $this
     */
    public function setDeadline(?\DateTime $deadline = null): self
    {
        $this->deadline = $deadline;

        return $this;
    }
}


