<?php
/**
 * PatchedPropertyRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the PatchedPropertyRequest model.
 *
 * Adds nested create feature
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class PatchedPropertyRequest 
{
        /**
     * @var PropertyDefinitionRequest|null
     * @SerializedName("definition")
     * @Assert\Type("OpenAPI\Server\Model\PropertyDefinitionRequest")
     * @Type("OpenAPI\Server\Model\PropertyDefinitionRequest")
     */
    protected ?PropertyDefinitionRequest $definition = null;

    /**
     * @var array|null
     * @SerializedName("value")
     * @Assert\All({
     *   @Assert\Type("AnyType")
     * })
     * @Type("array<string, AnyType>")
     */
    protected ?array $value = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->definition = $data['definition'] ?? null;
        $this->value = $data['value'] ?? null;
    }

    /**
     * Gets definition.
     *
     * @return PropertyDefinitionRequest|null
     */
    public function getDefinition(): ?PropertyDefinitionRequest
    {
        return $this->definition;
    }

    /**
     * Sets definition.
     *
     * @param PropertyDefinitionRequest|null $definition
     *
     * @return $this
     */
    public function setDefinition(?PropertyDefinitionRequest $definition = null): self
    {
        $this->definition = $definition;

        return $this;
    }

    /**
     * Gets value.
     *
     * @return array|null
     */
    public function getValue(): ?array
    {
        return $this->value;
    }

    /**
     * Sets value.
     *
     * @param array|null $value
     *
     * @return $this
     */
    public function setValue(?array $value = null): self
    {
        $this->value = $value;

        return $this;
    }
}


