<?php
/**
 * PatchedVisaCommentRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the PatchedVisaCommentRequest model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class PatchedVisaCommentRequest 
{
        /**
     * This is the userproject_id. This field is only used if the call is made from an App
     *
     * @var int|null
     * @SerializedName("author_id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $authorId = null;

    /**
     * @var string|null
     * @SerializedName("content")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $content = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->authorId = $data['authorId'] ?? null;
        $this->content = $data['content'] ?? null;
    }

    /**
     * Gets authorId.
     *
     * @return int|null
     */
    public function getAuthorId(): ?int
    {
        return $this->authorId;
    }

    /**
     * Sets authorId.
     *
     * @param int|null $authorId  This is the userproject_id. This field is only used if the call is made from an App
     *
     * @return $this
     */
    public function setAuthorId(?int $authorId = null): self
    {
        $this->authorId = $authorId;

        return $this;
    }

    /**
     * Gets content.
     *
     * @return string|null
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * Sets content.
     *
     * @param string|null $content
     *
     * @return $this
     */
    public function setContent(?string $content = null): self
    {
        $this->content = $content;

        return $this;
    }
}


