<?php
/**
 * ProcessorHandler
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ProcessorHandler model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class ProcessorHandler 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $id = null;

    /**
     * @var string|null
     * @SerializedName("worker")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $worker = null;

    /**
     * @var string|null
     * @SerializedName("status")
     * @Assert\Choice({ "C", "D", "P", "W", "I", "E", "X" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $status = null;

    /**
     * @var string|null
     * @SerializedName("detail_message")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $detailMessage = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = $data['id'] ?? null;
        $this->worker = $data['worker'] ?? null;
        $this->status = $data['status'] ?? null;
        $this->detailMessage = $data['detailMessage'] ?? null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id
     *
     * @return $this
     */
    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets worker.
     *
     * @return string|null
     */
    public function getWorker(): ?string
    {
        return $this->worker;
    }

    /**
     * Sets worker.
     *
     * @param string|null $worker
     *
     * @return $this
     */
    public function setWorker(?string $worker): self
    {
        $this->worker = $worker;

        return $this;
    }

    /**
     * Gets status.
     *
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets status.
     *
     * @param string|null $status
     *
     * @return $this
     */
    public function setStatus(?string $status = null): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Gets detailMessage.
     *
     * @return string|null
     */
    public function getDetailMessage(): ?string
    {
        return $this->detailMessage;
    }

    /**
     * Sets detailMessage.
     *
     * @param string|null $detailMessage
     *
     * @return $this
     */
    public function setDetailMessage(?string $detailMessage = null): self
    {
        $this->detailMessage = $detailMessage;

        return $this;
    }
}


