<?php
/**
 * ProjectAccessTokenRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ProjectAccessTokenRequest model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class ProjectAccessTokenRequest 
{
        /**
     * @var array|null
     * @SerializedName("scopes")
     * @Assert\NotNull()
     * @Assert\All({
     *   @Assert\Choice({ "bcf:read", "bcf:write", "document:read", "document:write", "ifc:read", "ifc:write", "model:read", "model:write" })
     * })
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected ?array $scopes = null;

    /**
     * @var \DateTime|null
     * @SerializedName("expires_at")
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected ?\DateTime $expiresAt = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->scopes = $data['scopes'] ?? null;
        $this->expiresAt = $data['expiresAt'] ?? null;
    }

    /**
     * Gets scopes.
     *
     * @return array|null
     */
    public function getScopes(): ?array
    {
        return $this->scopes;
    }

    /**
     * Sets scopes.
     *
     * @param array|null $scopes
     *
     * @return $this
     */
    public function setScopes(?array $scopes): self
    {
        $this->scopes = $scopes;

        return $this;
    }

    /**
     * Gets expiresAt.
     *
     * @return \DateTime|null
     */
    public function getExpiresAt(): ?\DateTime
    {
        return $this->expiresAt;
    }

    /**
     * Sets expiresAt.
     *
     * @param \DateTime|null $expiresAt
     *
     * @return $this
     */
    public function setExpiresAt(?\DateTime $expiresAt = null): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }
}


