<?php
/**
 * RawMaterialList
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RawMaterialList model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class RawMaterialList 
{
        /**
     * @var array|null
     * @SerializedName("materials_data")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\RawMaterial")
     * })
     * @Type("array<OpenAPI\Server\Model\RawMaterial>")
     */
    protected ?array $materialsData = null;

    /**
     * @var array|null
     * @SerializedName("list_components")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\RawMaterialListComponents")
     * })
     * @Type("array<OpenAPI\Server\Model\RawMaterialListComponents>")
     */
    protected ?array $listComponents = null;

    /**
     * @var array|null
     * @SerializedName("options")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\RawMaterialOptions")
     * })
     * @Type("array<OpenAPI\Server\Model\RawMaterialOptions>")
     */
    protected ?array $options = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->materialsData = $data['materialsData'] ?? null;
        $this->listComponents = $data['listComponents'] ?? null;
        $this->options = $data['options'] ?? null;
    }

    /**
     * Gets materialsData.
     *
     * @return array|null
     */
    public function getMaterialsData(): ?array
    {
        return $this->materialsData;
    }

    /**
     * Sets materialsData.
     *
     * @param array|null $materialsData
     *
     * @return $this
     */
    public function setMaterialsData(?array $materialsData = null): self
    {
        $this->materialsData = $materialsData;

        return $this;
    }

    /**
     * Gets listComponents.
     *
     * @return array|null
     */
    public function getListComponents(): ?array
    {
        return $this->listComponents;
    }

    /**
     * Sets listComponents.
     *
     * @param array|null $listComponents
     *
     * @return $this
     */
    public function setListComponents(?array $listComponents = null): self
    {
        $this->listComponents = $listComponents;

        return $this;
    }

    /**
     * Gets options.
     *
     * @return array|null
     */
    public function getOptions(): ?array
    {
        return $this->options;
    }

    /**
     * Sets options.
     *
     * @param array|null $options
     *
     * @return $this
     */
    public function setOptions(?array $options = null): self
    {
        $this->options = $options;

        return $this;
    }
}


