<?php
/**
 * ZoneRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ZoneRequest model.
 *
 * Adds nested create feature
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class ZoneRequest 
{
        /**
     * @var string|null
     * @SerializedName("name")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 255
     * )
     */
    protected ?string $name = null;

    /**
     * @var string|null
     * @SerializedName("uuid")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 512
     * )
     * @Assert\Length(
     *   min = 1
     * )
     */
    protected ?string $uuid = null;

    /**
     * @var array|null
     * @SerializedName("zones")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\ZoneRequest")
     * })
     * @Type("array<OpenAPI\Server\Model\ZoneRequest>")
     */
    protected ?array $zones = null;

    /**
     * @var int|null
     * @SerializedName("parent_id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $parentId = null;

    /**
     * @var array|null
     * @SerializedName("spaces")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\SpaceRequest")
     * })
     * @Type("array<OpenAPI\Server\Model\SpaceRequest>")
     */
    protected ?array $spaces = null;

    /**
     * @var string|null
     * @SerializedName("color")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 8
     * )
     */
    protected ?string $color = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->name = $data['name'] ?? null;
        $this->uuid = $data['uuid'] ?? null;
        $this->zones = $data['zones'] ?? null;
        $this->parentId = $data['parentId'] ?? null;
        $this->spaces = $data['spaces'] ?? null;
        $this->color = $data['color'] ?? null;
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name
     *
     * @return $this
     */
    public function setName(?string $name = null): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets uuid.
     *
     * @return string|null
     */
    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    /**
     * Sets uuid.
     *
     * @param string|null $uuid
     *
     * @return $this
     */
    public function setUuid(?string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * Gets zones.
     *
     * @return array|null
     */
    public function getZones(): ?array
    {
        return $this->zones;
    }

    /**
     * Sets zones.
     *
     * @param array|null $zones
     *
     * @return $this
     */
    public function setZones(?array $zones = null): self
    {
        $this->zones = $zones;

        return $this;
    }

    /**
     * Gets parentId.
     *
     * @return int|null
     */
    public function getParentId(): ?int
    {
        return $this->parentId;
    }

    /**
     * Sets parentId.
     *
     * @param int|null $parentId
     *
     * @return $this
     */
    public function setParentId(?int $parentId = null): self
    {
        $this->parentId = $parentId;

        return $this;
    }

    /**
     * Gets spaces.
     *
     * @return array|null
     */
    public function getSpaces(): ?array
    {
        return $this->spaces;
    }

    /**
     * Sets spaces.
     *
     * @param array|null $spaces
     *
     * @return $this
     */
    public function setSpaces(?array $spaces = null): self
    {
        $this->spaces = $spaces;

        return $this;
    }

    /**
     * Gets color.
     *
     * @return string|null
     */
    public function getColor(): ?string
    {
        return $this->color;
    }

    /**
     * Sets color.
     *
     * @param string|null $color
     *
     * @return $this
     */
    public function setColor(?string $color = null): self
    {
        $this->color = $color;

        return $this;
    }
}


