<?php
/**
 * ExtensionsTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * ExtensionsTest Class Doc Comment
 *
 * @category    Class
 * @description Extensions
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\Extensions
 */
class ExtensionsTest extends TestCase
{
    protected Extensions|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(Extensions::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(Extensions::class));
        $this->assertInstanceOf(Extensions::class, $this->object);
    }

    /**
     * Test attribute "topicType"
     *
     * @group unit
     * @small
     */
    public function testPropertyTopicType(): void
    {
        $this->markTestSkipped('Test for property topicType not implemented');
    }

    /**
     * Test attribute "topicStatus"
     *
     * @group unit
     * @small
     */
    public function testPropertyTopicStatus(): void
    {
        $this->markTestSkipped('Test for property topicStatus not implemented');
    }

    /**
     * Test attribute "topicLabel"
     *
     * @group unit
     * @small
     */
    public function testPropertyTopicLabel(): void
    {
        $this->markTestSkipped('Test for property topicLabel not implemented');
    }

    /**
     * Test attribute "priority"
     *
     * @group unit
     * @small
     */
    public function testPropertyPriority(): void
    {
        $this->markTestSkipped('Test for property priority not implemented');
    }

    /**
     * Test attribute "stage"
     *
     * @group unit
     * @small
     */
    public function testPropertyStage(): void
    {
        $this->markTestSkipped('Test for property stage not implemented');
    }

    /**
     * Test attribute "userIdType"
     *
     * @group unit
     * @small
     */
    public function testPropertyUserIdType(): void
    {
        $this->markTestSkipped('Test for property userIdType not implemented');
    }

    /**
     * Test attribute "priorityColors"
     *
     * @group unit
     * @small
     */
    public function testPropertyPriorityColors(): void
    {
        $this->markTestSkipped('Test for property priorityColors not implemented');
    }

    /**
     * Test attribute "topicStatusColors"
     *
     * @group unit
     * @small
     */
    public function testPropertyTopicStatusColors(): void
    {
        $this->markTestSkipped('Test for property topicStatusColors not implemented');
    }
}
