<?php
/**
 * ModelFilesTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * ModelFilesTest Class Doc Comment
 *
 * @category    Class
 * @description ModelFiles
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\ModelFiles
 */
class ModelFilesTest extends TestCase
{
    protected ModelFiles|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(ModelFiles::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(ModelFiles::class));
        $this->assertInstanceOf(ModelFiles::class, $this->object);
    }

    /**
     * Test attribute "structureFile"
     *
     * @group unit
     * @small
     */
    public function testPropertyStructureFile(): void
    {
        $this->markTestSkipped('Test for property structureFile not implemented');
    }

    /**
     * Test attribute "systemsFile"
     *
     * @group unit
     * @small
     */
    public function testPropertySystemsFile(): void
    {
        $this->markTestSkipped('Test for property systemsFile not implemented');
    }

    /**
     * Test attribute "mapFile"
     *
     * @group unit
     * @small
     */
    public function testPropertyMapFile(): void
    {
        $this->markTestSkipped('Test for property mapFile not implemented');
    }

    /**
     * Test attribute "gltfFile"
     *
     * @group unit
     * @small
     */
    public function testPropertyGltfFile(): void
    {
        $this->markTestSkipped('Test for property gltfFile not implemented');
    }

    /**
     * Test attribute "gltfWithOpeningsFile"
     *
     * @group unit
     * @small
     */
    public function testPropertyGltfWithOpeningsFile(): void
    {
        $this->markTestSkipped('Test for property gltfWithOpeningsFile not implemented');
    }

    /**
     * Test attribute "bvhTreeFile"
     *
     * @group unit
     * @small
     */
    public function testPropertyBvhTreeFile(): void
    {
        $this->markTestSkipped('Test for property bvhTreeFile not implemented');
    }

    /**
     * Test attribute "previewFile"
     *
     * @group unit
     * @small
     */
    public function testPropertyPreviewFile(): void
    {
        $this->markTestSkipped('Test for property previewFile not implemented');
    }

    /**
     * Test attribute "xktFile"
     *
     * @group unit
     * @small
     */
    public function testPropertyXktFile(): void
    {
        $this->markTestSkipped('Test for property xktFile not implemented');
    }
}
