<?php
/**
 * SelfUserTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * SelfUserTest Class Doc Comment
 *
 * @category    Class
 * @description SelfUser
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\SelfUser
 */
class SelfUserTest extends TestCase
{
    protected SelfUser|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(SelfUser::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(SelfUser::class));
        $this->assertInstanceOf(SelfUser::class, $this->object);
    }

    /**
     * Test attribute "id"
     *
     * @group unit
     * @small
     */
    public function testPropertyId(): void
    {
        $this->markTestSkipped('Test for property id not implemented');
    }

    /**
     * Test attribute "email"
     *
     * @group unit
     * @small
     */
    public function testPropertyEmail(): void
    {
        $this->markTestSkipped('Test for property email not implemented');
    }

    /**
     * Test attribute "firstname"
     *
     * @group unit
     * @small
     */
    public function testPropertyFirstname(): void
    {
        $this->markTestSkipped('Test for property firstname not implemented');
    }

    /**
     * Test attribute "lastname"
     *
     * @group unit
     * @small
     */
    public function testPropertyLastname(): void
    {
        $this->markTestSkipped('Test for property lastname not implemented');
    }

    /**
     * Test attribute "createdAt"
     *
     * @group unit
     * @small
     */
    public function testPropertyCreatedAt(): void
    {
        $this->markTestSkipped('Test for property createdAt not implemented');
    }

    /**
     * Test attribute "updatedAt"
     *
     * @group unit
     * @small
     */
    public function testPropertyUpdatedAt(): void
    {
        $this->markTestSkipped('Test for property updatedAt not implemented');
    }

    /**
     * Test attribute "organizations"
     *
     * @group unit
     * @small
     */
    public function testPropertyOrganizations(): void
    {
        $this->markTestSkipped('Test for property organizations not implemented');
    }

    /**
     * Test attribute "clouds"
     *
     * @group unit
     * @small
     */
    public function testPropertyClouds(): void
    {
        $this->markTestSkipped('Test for property clouds not implemented');
    }

    /**
     * Test attribute "projects"
     *
     * @group unit
     * @small
     */
    public function testPropertyProjects(): void
    {
        $this->markTestSkipped('Test for property projects not implemented');
    }

    /**
     * Test attribute "provider"
     *
     * @group unit
     * @small
     */
    public function testPropertyProvider(): void
    {
        $this->markTestSkipped('Test for property provider not implemented');
    }

    /**
     * Test attribute "providerSub"
     *
     * @group unit
     * @small
     */
    public function testPropertyProviderSub(): void
    {
        $this->markTestSkipped('Test for property providerSub not implemented');
    }

    /**
     * Test attribute "sub"
     *
     * @group unit
     * @small
     */
    public function testPropertySub(): void
    {
        $this->markTestSkipped('Test for property sub not implemented');
    }

    /**
     * Test attribute "profilePicture"
     *
     * @group unit
     * @small
     */
    public function testPropertyProfilePicture(): void
    {
        $this->markTestSkipped('Test for property profilePicture not implemented');
    }
}
