<?php
/**
 * ViewpointRequestTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * ViewpointRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Adds nested create feature
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\ViewpointRequest
 */
class ViewpointRequestTest extends TestCase
{
    protected ViewpointRequest|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(ViewpointRequest::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(ViewpointRequest::class));
        $this->assertInstanceOf(ViewpointRequest::class, $this->object);
    }

    /**
     * Test attribute "index"
     *
     * @group unit
     * @small
     */
    public function testPropertyIndex(): void
    {
        $this->markTestSkipped('Test for property index not implemented');
    }

    /**
     * Test attribute "guid"
     *
     * @group unit
     * @small
     */
    public function testPropertyGuid(): void
    {
        $this->markTestSkipped('Test for property guid not implemented');
    }

    /**
     * Test attribute "originatingSystem"
     *
     * @group unit
     * @small
     */
    public function testPropertyOriginatingSystem(): void
    {
        $this->markTestSkipped('Test for property originatingSystem not implemented');
    }

    /**
     * Test attribute "authoringToolId"
     *
     * @group unit
     * @small
     */
    public function testPropertyAuthoringToolId(): void
    {
        $this->markTestSkipped('Test for property authoringToolId not implemented');
    }

    /**
     * Test attribute "orthogonalCamera"
     *
     * @group unit
     * @small
     */
    public function testPropertyOrthogonalCamera(): void
    {
        $this->markTestSkipped('Test for property orthogonalCamera not implemented');
    }

    /**
     * Test attribute "perspectiveCamera"
     *
     * @group unit
     * @small
     */
    public function testPropertyPerspectiveCamera(): void
    {
        $this->markTestSkipped('Test for property perspectiveCamera not implemented');
    }

    /**
     * Test attribute "lines"
     *
     * @group unit
     * @small
     */
    public function testPropertyLines(): void
    {
        $this->markTestSkipped('Test for property lines not implemented');
    }

    /**
     * Test attribute "clippingPlanes"
     *
     * @group unit
     * @small
     */
    public function testPropertyClippingPlanes(): void
    {
        $this->markTestSkipped('Test for property clippingPlanes not implemented');
    }

    /**
     * Test attribute "snapshot"
     *
     * @group unit
     * @small
     */
    public function testPropertySnapshot(): void
    {
        $this->markTestSkipped('Test for property snapshot not implemented');
    }

    /**
     * Test attribute "components"
     *
     * @group unit
     * @small
     */
    public function testPropertyComponents(): void
    {
        $this->markTestSkipped('Test for property components not implemented');
    }

    /**
     * Test attribute "pins"
     *
     * @group unit
     * @small
     */
    public function testPropertyPins(): void
    {
        $this->markTestSkipped('Test for property pins not implemented');
    }

    /**
     * Test attribute "tempId"
     *
     * @group unit
     * @small
     */
    public function testPropertyTempId(): void
    {
        $this->markTestSkipped('Test for property tempId not implemented');
    }
}
